### PR TITLE
[Merged by Bors] - Refactor caching

### PR DESCRIPTION
**Pull request by OskarPersson**
* Makes cache_storage on storage policy optional
* Adds `cached` field to StorageMethod to indicate if it should be cached or not when accessed

### CODE REVIEW

**Comment by henrikek** [comment]
After disabling all storage methods that are not of the long-term type, files cannot be retrieved from the already stored IP:s.

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/ESSArch_Core/ip/views.py", line 1765, in files
    ip.open_file(path, 'rb'),
  File "/code/ESSArch_Core/ip/models.py", line 1807, in open_file
    return storage_obj.open(path, *args, **kwargs)
  File "/code/ESSArch_Core/storage/models.py", line 809, in open
    extracted = self.extract()
  File "/code/ESSArch_Core/storage/models.py", line 790, in extract
    storage_target__methods__storage_policy=policy).first()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1350, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1381, in _add_q
    check_filterable=check_filterable,
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1284, in build_filter
    self.check_related_objects(join_info.final_field, value, join_info.opts)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1122, in check_related_objects
    self.check_query_object_type(value, opts, field)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1105, in check_query_object_type
    (value, opts.object_name))

Exception Type: ValueError at /api/information-packages/14ba90d6-77b2-4b1f-b2bd-0d2d276666d1/files/
Exception Value: Cannot query "default": Must be "StorageMethod" instance.

**Comment by OskarPersson** [comment]
@henrikek This is fixed in #1141

**Comment by henrikek** [comment]
Accessing individual files in already archived IPs is now working properly.

I discovered some problems when archiving new IPs as below:

#############
Problem 1 - If you have storage methods that are included in storage policy but that any storage method is disabled, IP is still marked as archived. Task for writing to inactive storage method should be marked with errors in the Tasks tree.

#############
Problem 2 - If you try to access the tasks tree after ip is archived, you get the following traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/ESSArch_Core/WorkflowEngine/views.py", line 63, in list
    step = ProcessStep.objects.get(pk=parent_lookup_processstep)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 417, in get
    self.model._meta.object_name

Exception Type: DoesNotExist at /api/steps/407a3282-c10b-43da-94aa-0abbbe81a98e/children/
Exception Value: ProcessStep matching query does not exist.

#############
Problem 3 - If you try to access the menu "Storage migration" or "Storage maintenance" you get the following traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rest_framework/fields.py", line 454, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/fields.py", line 94, in get_attribute
    instance = getattr(instance, attr)

During handling of the above exception ('StorageMethod' object has no attribute 'entity'), another exception occurred:
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 760, in data
    ret = super().data
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 260, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 678, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 678, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 529, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 516, in to_representation
    attribute = field.get_attribute(instance)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/fields.py", line 487, in get_attribute
    raise type(exc)(msg)

Exception Type: AttributeError at /api/storage-policies/
Exception Value: Got AttributeError when attempting to get a value for field `entity` on serializer `PathSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `StorageMethod` instance.
Original exception text was: 'StorageMethod' object has no attribute 'entity'.

**Comment by OskarPersson** [comment]
Problem 1 and 3 are now fixed. How can I reproduce problem 2?

**Comment by henrikek** [comment]
It seems that problem 2 is related to performance performance issues and possibly a frontend issue. Hard to reproduce. Since this is not related to this PR, we are ignoring this problem right now.

**Comment by henrikek** [comment]
I discovered some more problems when archiving new IPs as below:

#######
Problem 4 - When preserve a new IP to a storage medium "Default Storage Disk 1" is marked with status inactive, a new storage medium with the name "DISK_Default Storage Target 1" is created. The above also applies if storage medium status is set to status FAIL or FULL. If storage media is a tape then an attempt to mount new tape should be made.The workflow should be stopped in the same way as if the Storage method is marked with status inactive. 

#######
Problem 5 - If you have two storage methods that are inactive when trying to archive a new IP, the workflow is stopped. If you then activate these storage methods and first do "retry" for writing to the first storage method, then it works well, the problem is that the IP is marked as archived even though there is still a storage method that has failed. If you also try to click "retry" for the next storage method, you get the following traceback which is not so strange:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/code/ESSArch_Core/WorkflowEngine/dbtask.py", line 89, in __call__
    return self._run(*args, **kwargs)
  File "/code/ESSArch_Core/WorkflowEngine/dbtask.py", line 111, in _run
    r = self._run_task(*args, **kwargs)
  File "/code/ESSArch_Core/WorkflowEngine/dbtask.py", line 127, in _run_task
    res = self.run(*args, **kwargs)
  File "/code/ESSArch_Core/ip/tasks.py", line 483, in run
    return ip.preserve(src, storage_target, storage_method.containers, self.get_processtask())
  File "/usr/local/lib/python3.7/site-packages/tenacity/__init__.py", line 311, in wrapped_f
    return self.call(f, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/tenacity/__init__.py", line 391, in call
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.7/site-packages/tenacity/__init__.py", line 338, in iter
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/site-packages/tenacity/__init__.py", line 394, in call
    result = fn(*args, **kwargs)
  File "/code/ESSArch_Core/ip/models.py", line 1782, in preserve
    storage_object = storage_backend.write(src, self, container, storage_medium)
  File "/code/ESSArch_Core/storage/backends/disk.py", line 76, in write
    new = copy(f, dst, block_size=block_size)
  File "/code/ESSArch_Core/storage/copy.py", line 239, in copy
    raise FileNotFoundError(errno.ENOENT, os.strerror(errno.ENOENT), src)
FileNotFoundError: [Errno 2] No such file or directory: '/ESSArch/data/ingest/packages/7732fa6c-b922-4472-945a-af19052ba4a5'

#######
Problem 6 - When preserve a new IP to a storage method that is active but the storage target is marked as inactive. Archiving of IP goes through and is marked as archived. The workflow should be stopped in the same way as if the Storage method is marked with status inactive.

**Comment by OskarPersson** [comment]
Problem 6 fixed in https://github.com/ESSolutions/ESSArch/pull/1038/commits/4fb1966be33ec7606a9787fbcc3cc93bdbc3d4c3

**Comment by henrikek** [comment]
bors retry

**Pull request closed without merging**
